PATCH http://localhost:3000/users/me
{
"name": "Пользователь 1",
"about": "Ничего себе"
}

###

PATCH http://localhost:3000/cards
Content-Type: application/json
{
    "name": "Первая карточка",
    "link": "https://yandex.ru/images/search?utm_source=main_stripe_big&text=%D0%9D%D1%8C%D1%8E-%D0%B9%D0%BE%D1%80%D0%BA%20%D0%A1%D0%B8%D1%82%D0%B8&nl=1&source=morda"
}

###